In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import pandas as pd

Train File

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Stylumia/train.tsv', sep='\t')

In [4]:
df.head()

url  ...  label
0  http://www.bloomberg.com/news/2010-12-23/ibm-p...  ...      0
1  http://www.popsci.com/technology/article/2012-...  ...      1
2  http://www.menshealth.com/health/flu-fighting-...  ...      1
3  http://www.dumblittleman.com/2007/12/10-foolpr...  ...      1
4  http://bleacherreport.com/articles/1205138-the...  ...      0

[5 rows x 27 columns]

In [5]:
df['is_news'].unique()

array(['1', '?'], dtype=object)

In [6]:
df.tail()

url  ...  label
7390  http://techcrunch.com/2010/09/08/kno-raises-46...  ...      0
7391  http://www.uncoached.com/category/why-i-miss-c...  ...      0
7392  http://eatthis.menshealth.com/slide/sweet-pota...  ...      1
7393                          http://naturallyella.com/  ...      1
7394  http://sportsillustrated.cnn.com/2011_swimsuit...  ...      0

[5 rows x 27 columns]

In [7]:
df.isna().sum()

url                               0
urlid                             0
boilerplate                       0
alchemy_category                  0
alchemy_category_score            0
avglinksize                       0
commonlinkratio_1                 0
commonlinkratio_2                 0
commonlinkratio_3                 0
commonlinkratio_4                 0
compression_ratio                 0
embed_ratio                       0
framebased                        0
frameTagRatio                     0
hasDomainLink                     0
html_ratio                        0
image_ratio                       0
is_news                           0
lengthyLinkDomain                 0
linkwordscore                     0
news_front_page                   0
non_markup_alphanum_characters    0
numberOfLinks                     0
numwords_in_url                   0
parametrizedLinkRatio             0
spelling_errors_ratio             0
label                             0
dtype: int64

In [8]:
df.columns

Index(['url', 'urlid', 'boilerplate', 'alchemy_category',
       'alchemy_category_score', 'avglinksize', 'commonlinkratio_1',
       'commonlinkratio_2', 'commonlinkratio_3', 'commonlinkratio_4',
       'compression_ratio', 'embed_ratio', 'framebased', 'frameTagRatio',
       'hasDomainLink', 'html_ratio', 'image_ratio', 'is_news',
       'lengthyLinkDomain', 'linkwordscore', 'news_front_page',
       'non_markup_alphanum_characters', 'numberOfLinks', 'numwords_in_url',
       'parametrizedLinkRatio', 'spelling_errors_ratio', 'label'],
      dtype='object')

In [9]:
missing_values = '?'
df = pd.read_csv('/content/drive/MyDrive/Stylumia/train.tsv', sep='\t', na_values = missing_values)

In [10]:
df.tail()

url  ...  label
7390  http://techcrunch.com/2010/09/08/kno-raises-46...  ...      0
7391  http://www.uncoached.com/category/why-i-miss-c...  ...      0
7392  http://eatthis.menshealth.com/slide/sweet-pota...  ...      1
7393                          http://naturallyella.com/  ...      1
7394  http://sportsillustrated.cnn.com/2011_swimsuit...  ...      0

[5 rows x 27 columns]

In [11]:
df.isnull().sum()

url                                  0
urlid                                0
boilerplate                          0
alchemy_category                  2342
alchemy_category_score            2342
avglinksize                          0
commonlinkratio_1                    0
commonlinkratio_2                    0
commonlinkratio_3                    0
commonlinkratio_4                    0
compression_ratio                    0
embed_ratio                          0
framebased                           0
frameTagRatio                        0
hasDomainLink                        0
html_ratio                           0
image_ratio                          0
is_news                           2843
lengthyLinkDomain                    0
linkwordscore                        0
news_front_page                   1248
non_markup_alphanum_characters       0
numberOfLinks                        0
numwords_in_url                      0
parametrizedLinkRatio                0
spelling_errors_ratio    

In [12]:
df['alchemy_category'] = df['alchemy_category'].fillna('Unknown Category')
df['alchemy_category_score'].fillna(df['alchemy_category_score'].mean(),inplace=True)
df['is_news'] = df['is_news'].fillna('1')
df['news_front_page'].fillna(df['news_front_page'].mean(),inplace=True)

In [13]:
df.tail()

url  ...  label
7390  http://techcrunch.com/2010/09/08/kno-raises-46...  ...      0
7391  http://www.uncoached.com/category/why-i-miss-c...  ...      0
7392  http://eatthis.menshealth.com/slide/sweet-pota...  ...      1
7393                          http://naturallyella.com/  ...      1
7394  http://sportsillustrated.cnn.com/2011_swimsuit...  ...      0

[5 rows x 27 columns]

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
df['url'] = LabelEncoder().fit_transform(df['url'])
df['boilerplate'] = LabelEncoder().fit_transform(df['boilerplate'])
df['alchemy_category'] = LabelEncoder().fit_transform(df['alchemy_category'])

In [16]:
df.head()

url  urlid  ...  spelling_errors_ratio  label
0  3097   4042  ...               0.079130      0
1  5938   8471  ...               0.125448      1
2  5327   1164  ...               0.057613      1
3  3674   6684  ...               0.100858      1
4   359   9006  ...               0.082569      0

[5 rows x 27 columns]

In [17]:
df.tail()

url  urlid  ...  spelling_errors_ratio  label
7390  2364   8958  ...               0.071429      0
7391  6878   8895  ...               0.109453      0
7392   849   1191  ...               0.117647      1
7393  1666   5612  ...               0.333333      1
7394  2160     90  ...               0.134146      0

[5 rows x 27 columns]

In [18]:
df['label'].value_counts()

1    3796
0    3599
Name: label, dtype: int64

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
x = df.iloc[:,:-1]
y = df['label']

In [21]:
x = StandardScaler().fit_transform(x)

In [22]:
x

array([[-0.28106301, -0.41457706, -0.32952424, ...,  0.94013354,
        -0.10870584, -0.27883964],
       [ 1.04977036,  1.03842208,  0.63422556, ...,  1.24945404,
         0.04885672,  0.3058009 ],
       [ 0.76355452, -1.35874764, -0.58533727, ...,  1.86809504,
        -0.03381499, -0.5504239 ],
       ...,
       [-1.33411244, -1.34988989,  0.52178028, ...,  0.01217204,
         1.42599342,  0.20733554],
       [-0.9513983 ,  0.10048473, -0.0179571 , ..., -1.53443045,
        -0.79961612,  2.92976964],
       [-0.71998975, -1.71108927, -0.70527891, ..., -0.29714846,
        -0.91091784,  0.41559268]])

In [23]:
y

0       0
1       1
2       1
3       1
4       0
       ..
7390    0
7391    0
7392    1
7393    1
7394    0
Name: label, Length: 7395, dtype: int64

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
(x_train, x_val, y_train, y_val) = train_test_split(x, y, test_size = 0.2, random_state=42)

In [26]:
x_train

array([[-0.12413616, -0.74165769, -0.88472284, ..., -0.60646896,
        -0.6951887 ,  0.17431103],
       [ 1.23620882,  1.25297648,  0.45384458, ...,  0.01217204,
         0.38760911,  0.01458883],
       [ 0.63613929,  0.58274003, -1.55049264, ..., -1.53443045,
         0.6041145 ,  2.27236368],
       ...,
       [ 0.53167753,  0.47972767,  1.42602779, ..., -0.60646896,
        -0.48850941, -0.40627387],
       [-0.22485041, -0.75478029,  1.20020017, ..., -0.60646896,
         2.02126059, -0.41897583],
       [-0.2173554 ,  0.09097085,  1.20347982, ...,  0.63081304,
        -0.45311404,  0.11422427]])

In [27]:
x_train.shape

(5916, 26)

In [28]:
x_val

array([[-0.79072395, -0.76298191, -0.92970096, ..., -0.91578945,
        -0.01163478,  0.00558903],
       [ 1.17812247,  1.70931466, -0.23628836, ..., -0.29714846,
         1.1068635 , -0.27232099],
       [-0.84927874,  1.22541903,  0.19522042, ..., -1.53443045,
        -0.55559548, -0.42246629],
       ...,
       [-0.98746806,  0.58175583,  1.49583757, ...,  1.55877454,
        -0.94320383, -0.32730886],
       [ 1.70183655, -0.17804231, -1.14850074, ...,  0.01217204,
        -0.86354934,  0.12483753],
       [-1.01416904, -0.07043705, -1.61842833, ...,  0.94013354,
         2.07213812, -1.27762852]])

In [29]:
x_val.shape

(1479, 26)

In [30]:
y_train

4189    0
5144    1
3914    0
3918    0
2318    0
       ..
5191    0
5226    0
5390    1
860     1
7270    0
Name: label, Length: 5916, dtype: int64

In [31]:
y_train.shape

(5916,)

In [32]:
y_val

2759    1
2846    1
6681    1
3262    1
486     0
       ..
7391    0
6302    1
110     1
51      1
1109    1
Name: label, Length: 1479, dtype: int64

In [33]:
y_val.shape

(1479,)

Test File

In [34]:
df_test = pd.read_csv('/content/drive/MyDrive/Stylumia/test.tsv',sep='\t')

In [35]:
df_test.head()

url  ...  spelling_errors_ratio
0  http://www.lynnskitchenadventures.com/2009/04/...  ...               0.080597
1            http://lolpics.se/18552-stun-grenade-ar  ...               0.176471
2  http://www.xcelerationfitness.com/treadmills.html  ...               0.125000
3  http://www.bloomberg.com/news/2012-02-06/syria...  ...               0.063126
4  http://www.wired.com/gadgetlab/2011/12/stem-tu...  ...               0.065341

[5 rows x 26 columns]

In [36]:
df_test.tail()

url  ...  spelling_errors_ratio
3166  http://busy-mommy.com/2012/02/peep-brownie-smo...  ...               0.063401
3167  http://www.cannabissearch.com/edibles/cheesecake/  ...               0.061995
3168  http://www.tastespotting.com/popular/views/all...  ...               0.117647
3169  http://lifehacker.com/5839197/how-to-get-a-ful...  ...               0.111966
3170  http://www.howsweeteats.com/2011/03/crispy-par...  ...               0.130024

[5 rows x 26 columns]

In [37]:
missing_values = '?'
df_test = pd.read_csv('/content/drive/MyDrive/Stylumia/test.tsv', sep='\t', na_values = missing_values)

In [38]:
df_test.isna().sum()

url                                  0
urlid                                0
boilerplate                          0
alchemy_category                  1046
alchemy_category_score            1046
avglinksize                          0
commonlinkratio_1                    0
commonlinkratio_2                    0
commonlinkratio_3                    0
commonlinkratio_4                    0
compression_ratio                    0
embed_ratio                          0
framebased                           0
frameTagRatio                        0
hasDomainLink                        0
html_ratio                           0
image_ratio                          0
is_news                           1225
lengthyLinkDomain                    0
linkwordscore                        0
news_front_page                    583
non_markup_alphanum_characters       0
numberOfLinks                        0
numwords_in_url                      0
parametrizedLinkRatio                0
spelling_errors_ratio    

In [39]:
df_test.tail()

url  ...  spelling_errors_ratio
3166  http://busy-mommy.com/2012/02/peep-brownie-smo...  ...               0.063401
3167  http://www.cannabissearch.com/edibles/cheesecake/  ...               0.061995
3168  http://www.tastespotting.com/popular/views/all...  ...               0.117647
3169  http://lifehacker.com/5839197/how-to-get-a-ful...  ...               0.111966
3170  http://www.howsweeteats.com/2011/03/crispy-par...  ...               0.130024

[5 rows x 26 columns]

In [40]:
df_test['alchemy_category'] = df_test['alchemy_category'].fillna('Unknown Category')
df_test['alchemy_category_score'].fillna(df_test['alchemy_category_score'].mean(),inplace=True)
df_test['is_news'] = df_test['is_news'].fillna('1')
df_test['news_front_page'].fillna(df_test['news_front_page'].mean(),inplace=True)

In [41]:
df_test.tail()

url  ...  spelling_errors_ratio
3166  http://busy-mommy.com/2012/02/peep-brownie-smo...  ...               0.063401
3167  http://www.cannabissearch.com/edibles/cheesecake/  ...               0.061995
3168  http://www.tastespotting.com/popular/views/all...  ...               0.117647
3169  http://lifehacker.com/5839197/how-to-get-a-ful...  ...               0.111966
3170  http://www.howsweeteats.com/2011/03/crispy-par...  ...               0.130024

[5 rows x 26 columns]

In [42]:
df_test['url'] = LabelEncoder().fit_transform(df_test['url'])
df_test['boilerplate'] = LabelEncoder().fit_transform(df_test['boilerplate'])
df_test['alchemy_category'] = LabelEncoder().fit_transform(df_test['alchemy_category'])

In [43]:
df_test.head()

url  urlid  ...  parametrizedLinkRatio  spelling_errors_ratio
0  2257   5865  ...               0.242647               0.080597
1   659    782  ...               0.128205               0.176471
2  3093   6962  ...               0.581197               0.125000
3  1345   7640  ...               0.038835               0.063126
4  3056   3589  ...               0.096774               0.065341

[5 rows x 26 columns]

In [44]:
df_test.tail()

url  urlid  ...  parametrizedLinkRatio  spelling_errors_ratio
3166   277   7264  ...               0.012987               0.063401
3167  1398   9714  ...               0.333333               0.061995
3168  2788   5903  ...               0.177083               0.117647
3169   647   3176  ...               0.333333               0.111966
3170  1986   7441  ...               0.287154               0.130024

[5 rows x 26 columns]

In [45]:
df.columns

Index(['url', 'urlid', 'boilerplate', 'alchemy_category',
       'alchemy_category_score', 'avglinksize', 'commonlinkratio_1',
       'commonlinkratio_2', 'commonlinkratio_3', 'commonlinkratio_4',
       'compression_ratio', 'embed_ratio', 'framebased', 'frameTagRatio',
       'hasDomainLink', 'html_ratio', 'image_ratio', 'is_news',
       'lengthyLinkDomain', 'linkwordscore', 'news_front_page',
       'non_markup_alphanum_characters', 'numberOfLinks', 'numwords_in_url',
       'parametrizedLinkRatio', 'spelling_errors_ratio', 'label'],
      dtype='object')

In [46]:
df_test.columns

Index(['url', 'urlid', 'boilerplate', 'alchemy_category',
       'alchemy_category_score', 'avglinksize', 'commonlinkratio_1',
       'commonlinkratio_2', 'commonlinkratio_3', 'commonlinkratio_4',
       'compression_ratio', 'embed_ratio', 'framebased', 'frameTagRatio',
       'hasDomainLink', 'html_ratio', 'image_ratio', 'is_news',
       'lengthyLinkDomain', 'linkwordscore', 'news_front_page',
       'non_markup_alphanum_characters', 'numberOfLinks', 'numwords_in_url',
       'parametrizedLinkRatio', 'spelling_errors_ratio'],
      dtype='object')

In [47]:
x_test = df_test

In [48]:
x_test.head()

url  urlid  ...  parametrizedLinkRatio  spelling_errors_ratio
0  2257   5865  ...               0.242647               0.080597
1   659    782  ...               0.128205               0.176471
2  3093   6962  ...               0.581197               0.125000
3  1345   7640  ...               0.038835               0.063126
4  3056   3589  ...               0.096774               0.065341

[5 rows x 26 columns]

In [49]:
x_test = StandardScaler().fit_transform(x_test)

In [50]:
x_test

array([[ 0.73411429,  0.20735578, -0.44898954, ..., -0.56902981,
         0.40608222, -0.25583941],
       [-1.01159201, -1.45697068,  1.01377687, ..., -0.88732114,
        -0.22275994,  0.91084661],
       [ 1.64738742,  0.56654644,  0.75924022, ..., -1.20561247,
         2.26636376,  0.28450075],
       ...,
       [ 1.31419566,  0.21979812, -0.08302483, ..., -0.25073849,
         0.04581886,  0.19502277],
       [-1.02470119, -0.67310337, -0.37688903, ...,  2.29559214,
         0.90439042,  0.1258853 ],
       [ 0.43806522,  0.72338539, -0.8542818 , ..., -0.25073849,
         0.65063963,  0.34563346]])

In [51]:
x_test.shape

(3171, 26)

Classification Model

1. *Random Forest Classifier*

In [52]:
from sklearn.ensemble import RandomForestClassifier

In [53]:
model = RandomForestClassifier(n_estimators=100, n_jobs=-1)
model.fit(x_train, y_train)

y_pred1 = model.predict(x_test)
print(y_pred1)

[1 0 0 ... 1 0 1]


In [54]:
rfr_train =  model.score(x_train, y_train)
rfr_test = model.score(x_val, y_val)
print('Training Accuracy: ', rfr_train)
print('Testing Accuracy: ', rfr_test)

Training Accuracy:  1.0
Testing Accuracy:  0.6923597025016903


In [55]:
import numpy as np
p = model.predict(x_val)
p = [np.argmax(t) for t in p]

In [56]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_val,p))

              precision    recall  f1-score   support

           0       0.49      1.00      0.66       730
           1       0.00      0.00      0.00       749

    accuracy                           0.49      1479
   macro avg       0.25      0.50      0.33      1479
weighted avg       0.24      0.49      0.33      1479



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


2. *K-Nearest Neighbours Classifier*

In [57]:
from sklearn.neighbors import KNeighborsClassifier

In [58]:
knc_model = KNeighborsClassifier()
knc_model.fit(x_train, y_train)

y_pred2 = knc_model.predict(x_test)
print(y_pred2)

[1 1 0 ... 0 0 1]


In [59]:
knc_train = model.score(x_train, y_train)
knc_test = model.score(x_val, y_val)

print('Training Accuracy: ', knc_train)
print('Testing Accuracy: ', knc_test)

Training Accuracy:  1.0
Testing Accuracy:  0.6923597025016903


In [60]:
knc_p = knc_model.predict(x_val)
knc_p = [np.argmax(k) for k in knc_p]

In [61]:
print(classification_report(y_val,knc_p))

              precision    recall  f1-score   support

           0       0.49      1.00      0.66       730
           1       0.00      0.00      0.00       749

    accuracy                           0.49      1479
   macro avg       0.25      0.50      0.33      1479
weighted avg       0.24      0.49      0.33      1479



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


3. *Support Vector Machine Classifier*

In [62]:
from sklearn.svm import SVC

In [63]:
svc_model = SVC(kernel='rbf')
svc_model.fit(x_train, y_train)

y_pred3 = svc_model.predict(x_test)
print(y_pred3)

[1 0 0 ... 1 0 1]


In [64]:
svc_train = svc_model.score(x_train, y_train)
svc_test = svc_model.score(x_val, y_val)

print('Training Accuracy: ', svc_train)
print('Testing Accuracy: ', svc_test)

Training Accuracy:  0.7327586206896551
Testing Accuracy:  0.656524678837052


In [65]:
svc_p = svc_model.predict(x_val)
svc_p = [np.argmax(r) for r in svc_p]

In [66]:
print(classification_report(y_val,svc_p))

              precision    recall  f1-score   support

           0       0.49      1.00      0.66       730
           1       0.00      0.00      0.00       749

    accuracy                           0.49      1479
   macro avg       0.25      0.50      0.33      1479
weighted avg       0.24      0.49      0.33      1479



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


4. *XGBoost Classifier*

In [67]:
from xgboost import XGBClassifier

In [68]:
xgb_model = XGBClassifier()
xgb_model.fit(x_train, y_train)

y_pred4 = xgb_model.predict(x_test)
print(y_pred4)

[1 0 0 ... 1 0 1]


In [69]:
xgb_train = xgb_model.score(x_train, y_train)
xgb_test = xgb_model.score(x_val, y_val)

print('Training Accuracy: ', xgb_train)
print('Testing Accuracy: ', xgb_test)

Training Accuracy:  0.7528735632183908
Testing Accuracy:  0.6883029073698445


In [70]:
xgb_p = xgb_model.predict(x_val)
xgb_p = [np.argmax(r) for r in xgb_p]

In [71]:
print(classification_report(y_val,xgb_p))

              precision    recall  f1-score   support

           0       0.49      1.00      0.66       730
           1       0.00      0.00      0.00       749

    accuracy                           0.49      1479
   macro avg       0.25      0.50      0.33      1479
weighted avg       0.24      0.49      0.33      1479



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [72]:
table = [["Random Forest Classifier", rfr_train, rfr_test],["K-Nearest Neighbours Classifier",knc_train, knc_test],
...          ["Support Vector Machine Classifier", svc_train, svc_test],["XGBoost Classifier", xgb_train, xgb_test]]

from tabulate import tabulate
from IPython.display import HTML
HTML(tabulate(table, headers= ['Algorithm', ' Training Accuracy ',' Testing Accuracy '], tablefmt='html'))

Saving the Results

In [73]:
urlid = df_test.urlid

In [74]:
results = {'urlid':urlid, 'label':y_pred4}
final_result = pd.DataFrame(results)

final_result.to_csv('Results.csv', index=False)